"""
Cognitive analysis schemas for the SMRITI platform.

These models are consumed and produced by the AI intelligence engine
to represent processed cognitive scores, domain breakdowns, and
per-game analytics derived from raw game attempts.
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from .game import GameDifficulty, GameType


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class CognitiveDomain(str, Enum):
    """Cognitive domains assessed by the game battery."""
    MEMORY = "memory"
    ATTENTION = "attention"
    EXECUTIVE_FUNCTION = "executive_function"
    LANGUAGE = "language"
    VISUOSPATIAL = "visuospatial"


class TrendDirection(str, Enum):
    """Direction of a metric trend over a time window."""
    IMPROVING = "improving"
    STABLE = "stable"
    DECLINING = "declining"


# ---------------------------------------------------------------------------
# Domain Score
# ---------------------------------------------------------------------------

class CognitiveDomainScore(BaseModel):
    """Score for a single cognitive domain derived from game metrics."""
    domain: CognitiveDomain = Field(..., description="Cognitive domain.")
    score: float = Field(
        ..., ge=0.0, le=100.0, description="Normalised domain score (0–100)."
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Model confidence in this score (0.0–1.0).",
    )
    contributing_games: int = Field(
        ..., ge=0, description="Number of game attempts feeding this score."
    )
    trend: TrendDirection = Field(
        ..., description="Trend over the analysis window."
    )

    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------------------------
# Per-Game Summary
# ---------------------------------------------------------------------------

class GamePerformanceSummary(BaseModel):
    """Aggregated performance stats for a single game type."""
    game_type: GameType = Field(..., description="Game type.")
    attempts_count: int = Field(..., ge=0, description="Total attempts in window.")
    average_score: float = Field(
        ..., ge=0.0, le=100.0, description="Mean score."
    )
    average_reaction_time_ms: float = Field(
        ..., ge=0.0, description="Mean reaction time (ms)."
    )
    average_mistakes: float = Field(
        ..., ge=0.0, description="Mean mistake count."
    )
    best_score: int = Field(..., ge=0, le=100, description="Highest score.")
    worst_score: int = Field(..., ge=0, le=100, description="Lowest score.")
    most_played_difficulty: GameDifficulty = Field(
        ..., description="Most frequently played difficulty."
    )
    trend: TrendDirection = Field(
        ..., description="Score trend over the window."
    )

    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------------------------
# Full Cognitive Report
# ---------------------------------------------------------------------------

class CognitiveReport(BaseModel):
    """
    Comprehensive cognitive report generated by the AI engine.
    Consumed by the caregiver dashboard and ASHA triage views.
    """
    patient_id: str = Field(..., description="Patient UUID.")
    report_period_start: datetime = Field(
        ..., description="Start of the analysis window."
    )
    report_period_end: datetime = Field(
        ..., description="End of the analysis window."
    )
    overall_score: float = Field(
        ..., ge=0.0, le=100.0, description="Weighted composite cognitive score."
    )
    overall_trend: TrendDirection = Field(
        ..., description="Overall cognitive trend."
    )
    domain_scores: List[CognitiveDomainScore] = Field(
        default_factory=list, description="Per-domain score breakdown."
    )
    game_summaries: List[GamePerformanceSummary] = Field(
        default_factory=list, description="Per-game type performance summary."
    )
    total_sessions: int = Field(
        ..., ge=0, description="Sessions completed in the period."
    )
    total_games_played: int = Field(
        ..., ge=0, description="Total game attempts in the period."
    )
    engagement_rate: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Percentage of expected sessions actually completed.",
    )
    risk_flags: List[str] = Field(
        default_factory=list,
        description="AI-generated risk indicators (e.g. 'rapid_decline').",
    )
    recommendations: List[str] = Field(
        default_factory=list,
        description="AI-generated recommendations for the caregiver.",
    )
    generated_at: datetime = Field(
        ..., description="Timestamp when the report was generated."
    )

    model_config = ConfigDict(from_attributes=True)
