"""
Daily session schemas for the SMRITI platform.

A "session" wraps one sitting of cognitive games and optional check-in.
The Flutter app starts a session, the patient plays games, and the session
is completed with aggregate stats sent to the AI engine.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class SessionStatus(str, Enum):
    """Lifecycle states of a daily session."""
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    ABANDONED = "abandoned"


# ---------------------------------------------------------------------------
# Start
# ---------------------------------------------------------------------------

class DailySessionStart(BaseModel):
    """Payload when the patient begins a new daily session."""
    patient_id: str = Field(
        ...,
        description="UUID of the patient starting the session.",
    )
    client_session_id: str = Field(
        ...,
        description="UUID generated by the Flutter app for offline tracking.",
    )
    started_at: datetime = Field(
        ...,
        description="Client-side timestamp when the session was opened.",
    )
    device_info: Optional[str] = Field(
        default=None,
        max_length=500,
        description="Device model / OS version string for analytics.",
    )

    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------------------------
# Complete
# ---------------------------------------------------------------------------

class DailySessionComplete(BaseModel):
    """Payload submitted when the patient finishes or abandons a session."""
    session_id: str = Field(
        ...,
        description="Server or client session UUID being completed.",
    )
    status: SessionStatus = Field(
        default=SessionStatus.COMPLETED,
        description="Final status of the session.",
    )
    total_games_played: int = Field(
        ...,
        ge=0,
        description="Number of game attempts completed in this session.",
    )
    total_duration_seconds: int = Field(
        ...,
        ge=0,
        description="Total wall-clock duration of the session in seconds.",
    )
    average_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=100.0,
        description="Mean game score across all attempts in this session.",
    )
    completed_at: datetime = Field(
        ...,
        description="Client-side timestamp when the session ended.",
    )

    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------------------------
# Response
# ---------------------------------------------------------------------------

class DailySessionResponse(BaseModel):
    """Full session record returned by the API."""
    id: str = Field(..., description="Server-assigned session UUID.")
    patient_id: str = Field(..., description="Patient UUID.")
    client_session_id: str = Field(..., description="Client-generated session UUID.")
    status: SessionStatus = Field(..., description="Session lifecycle status.")
    started_at: datetime = Field(..., description="Session start timestamp.")
    completed_at: Optional[datetime] = Field(
        default=None,
        description="Session end timestamp (null if still in progress).",
    )
    total_games_played: int = Field(
        default=0,
        ge=0,
        description="Games played in session.",
    )
    total_duration_seconds: int = Field(
        default=0,
        ge=0,
        description="Total session duration.",
    )
    average_score: Optional[float] = Field(
        default=None,
        description="Mean score across session games.",
    )
    device_info: Optional[str] = Field(
        default=None,
        description="Device info string.",
    )
    created_at: datetime = Field(..., description="Record creation timestamp.")
    updated_at: datetime = Field(..., description="Last update timestamp.")

    model_config = ConfigDict(from_attributes=True)
